name: creating docker image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: build image
        run: Docker build . -file Dockerfile -t my-sample-app:$(date +%s)
    
